package com.net.util;

public enum Commands {
	
	CLIENT_SEND_SPRITE,
	CLIENT_SEND_GAMEOBJECT,
	CLIENT_SEND_SCENE,
	CLIENT_SEND_GAMEOBJECTS,
	CLIENT_SEND_ASSETS,
	CLIENT_GET_SPRITE,
	CLIENT_GET_SPRITES,
	CLIENT_GET_GAMEOBJECT,
	CLIENT_GET_SCENE,
	CLIENT_GET_SCENES,
	CLIENT_GET_ASSETS,
	SERVER_SEND_SPRITE,
	SERVER_SEND_SPRITES,
	SERVER_SEND_GAMEOBJECT,
	SERVER_SEND_SCENE,
	SERVER_SEND_SCENES,
	SERVER_SEND_GAMEOBJECTS,
	SERVER_SEND_ASSEST,
			
}
